# Copyright 2022 Vioshim
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from json import dump, load

from movepool import Movepool
from species import Legendary, Pokemon, Species, SpeciesDecoder, SpeciesEncoder

DIR = "resources\species.json"


def save(data: list[Species]):
    with open(DIR, mode="w") as file2:
        return dump(data, fp=file2, indent=4, cls=SpeciesEncoder)


if __name__ == "__main__":
    with open(DIR, mode="r") as file1:
        data: list[Species] = load(fp=file1, cls=SpeciesDecoder)
        aux = {x.id: x for x in data}

        def foo(text: str):
            if mon := aux.get(text):
                return mon.abilities
            return frozenset()

        def bar(text: str):
            if mon := aux.get(text):
                return mon.shape
            return "ERROR"

        aux["GROWLITHEHISUI"] = Pokemon(
            id="GROWLITHEHISUI",
            name="Growlithe Hisui",
            shape="Quadruped",
            base_image="https://www.serebii.net/swordshield/pokemon/058-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/058-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/058-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/058-h.png",
            types=["FIRE", "ROCK"],
            height=0.8,
            weight=22.7,
            HP=60,
            ATK=75,
            DEF=45,
            SPA=65,
            SPD=50,
            SPE=55,
            evolves_to=["ARCANINEHISUI"],
            movepool=Movepool.from_dict(
                level={
                    1: ["TACKLE"],
                    5: ["EMBER"],
                    9: ["BITE"],
                    15: ["FIREFANG"],
                    21: ["ROCKSLIDE"],
                    29: ["CRUNCH"],
                    37: ["DOUBLEEDGE"],
                    47: ["FLAREBLITZ"],
                },
                tutor=[
                    "FIREFANG",
                    "ROCKSMASH",
                    "AERIALACE",
                    "SWIFT",
                    "REST",
                    "ROCKSLIDE",
                    "IRONTAIL",
                    "SNARL",
                    "WILDCHARGE",
                    "OUTRAGE",
                    "PLAYROUGH",
                    "FLAMETHROWER",
                ],
            ),
            abilities=foo("GROWLITHE"),
        )
        aux["ARCANINEHISUI"] = Pokemon(
            id="ARCANINEHISUI",
            name="Arcanine Hisui",
            shape="Quadruped",
            base_image="https://www.serebii.net/swordshield/pokemon/059-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/059-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/059-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/059-h.png",
            types=["FIRE", "ROCK"],
            height=2,
            weight=168,
            HP=95,
            ATK=115,
            DEF=80,
            SPA=95,
            SPD=80,
            SPE=90,
            evolves_from="GROWLITHEHISUI",
            movepool=Movepool.from_dict(
                level={
                    1: ["TACKLE"],
                    5: ["EMBER"],
                    9: ["BITE"],
                    15: ["FIREFANG"],
                    21: ["ROCKSLIDE"],
                    29: ["CRUNCH", "RAGINGFURY"],
                    37: ["DOUBLEEDGE"],
                    47: ["FLAREBLITZ"],
                },
                tutor=[
                    "FIREFANG",
                    "THUNDERFANG",
                    "ROCKSMASH",
                    "BULLDOZE",
                    "AERIALACE",
                    "SWIFT",
                    "REST",
                    "ROCKSLIDE",
                    "IRONHEAD",
                    "IRONTAIL",
                    "SNARL",
                    "GIGAIMPACT",
                    "WILDCHARGE",
                    "STONEEDGE",
                    "OUTRAGE",
                    "PLAYROUGH",
                    "HYPERBEAM",
                    "FLAMETHROWER",
                ],
            ),
            abilities=foo("ARCANINE"),
        )
        aux["VOLTORBHISUI"] = Pokemon(
            id="VOLTORBHISUI",
            name="Voltorb Hisui",
            shape=bar("VOLTORB"),
            base_image="https://www.serebii.net/swordshield/pokemon/100-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/100-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/100-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/100-h.png",
            types=["ELECTRIC", "GRASS"],
            height=0.5,
            weight=13,
            HP=40,
            ATK=30,
            DEF=50,
            SPA=55,
            SPD=55,
            SPE=100,
            evolves_to=["ELECTRODEHISUI"],
            movepool=Movepool.from_dict(
                level={
                    1: ["THUNDERSHOCK"],
                    5: ["TACKLE"],
                    9: ["THUNDERWAVE"],
                    15: ["SPARK"],
                    21: ["ENERGYBALL"],
                    29: ["THUNDERBOLD"],
                    37: ["THUNDER"],
                    47: ["SELFDESTRUCT"],
                },
                tutor=[
                    "ICEBALL",
                    "SWIFT",
                    "MAGICALLEAF",
                    "REST",
                    "CHARGEBEAM",
                    "ENERGYBALL",
                    "WILDCHARGE",
                    "THUNDERBOLT",
                ],
            ),
            abilities=foo("VOLTORB"),
        )
        aux["ELECTRODEHISUI"] = Pokemon(
            id="ELECTRODEHISUI",
            name="Electrode Hisui",
            shape=bar("ELECTRODE"),
            base_image="https://www.serebii.net/swordshield/pokemon/101-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/101-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/101-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/101-h.png",
            types=["ELECTRIC", "GRASS"],
            height=1.2,
            weight=71,
            HP=60,
            ATK=50,
            DEF=70,
            SPA=80,
            SPD=80,
            SPE=150,
            evolves_from="VOLTORBHISUI",
            movepool=Movepool.from_dict(
                level={
                    1: ["THUNDERSHOCK"],
                    5: ["TACKLE"],
                    9: ["THUNDERWAVE"],
                    15: ["SPARK"],
                    21: ["ENERGYBALL"],
                    29: ["THUNDERBOLT"],
                    37: ["THUNDER"],
                    47: ["CHLOROBLAST", "SELFDESTRUCT"],
                },
                tutor=[
                    "ICEBALL",
                    "SWIFT",
                    "MAGICALLEAF",
                    "REST",
                    "CHARGEBEAM",
                    "ENERGYBALL",
                    "GIGAIMPACT",
                    "WILDCHARGE",
                    "HYPERBEAM",
                    "THUNDERBOLT",
                ],
            ),
            abilities=foo("ELECTRODE"),
        )
        aux["TYPHLOSIONHISUI"] = Pokemon(
            id="TYPHLOSIONHISUI",
            name="Typhlosion Hisui",
            shape=bar("TYPHLOSION"),
            base_image="https://www.serebii.net/swordshield/pokemon/157-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/157-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/157-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/157-h.png",
            types=["FIRE", "GHOST"],
            height=1.6,
            weight=69.8,
            HP=73,
            ATK=84,
            DEF=78,
            SPA=119,
            SPD=85,
            SPE=95,
            evolves_from="QUILAVA",
            movepool=Movepool.from_dict(
                level={
                    1: ["QUICKATTACK"],
                    6: ["EMBER"],
                    11: ["ROLLOUT"],
                    18: ["FLAMEWHEEL"],
                    25: ["SWIFT"],
                    34: ["FLAMETHROWER"],
                    40: ["INFERNALPARADE"],
                    43: ["SHADOWBALL", "OVERHEAT"],
                },
                tutor=[
                    "ROCKSMASH",
                    "BULLDOZE",
                    "AERIALACE",
                    "SWIFT",
                    "OMINOUSWIND",
                    "CALMMIND",
                    "REST",
                    "FIREPUNCH",
                    "THUNDERPUNCH",
                    "DRAINPUNCH",
                    "ROCKSLIDE",
                    "SHADOWCLAW",
                    "IRONTAIL",
                    "MYSTICALFIRE",
                    "SHADOWBALL",
                    "GIGAIMPACT",
                    "WILDCHARGE",
                    "HYPERBEAM",
                    "FLAMETHROWER",
                ],
                levelup=["HEX"],
            ),
            abilities=foo("TYPHLOSION"),
        )
        aux["QWILFISHHISUI"] = Pokemon(
            id="QWILFISHHISUI",
            name="Qwilfish Hisui",
            shape=bar("QWILFISH"),
            base_image="https://www.serebii.net/swordshield/pokemon/211-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/211-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/211-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/211-h.png",
            types=["DARK", "POISON"],
            height=0.5,
            weight=3.9,
            HP=65,
            ATK=95,
            DEF=85,
            SPA=55,
            SPD=55,
            SPE=85,
            evolves_to=["OVERQWIL"],
            movepool=Movepool.from_dict(
                level={
                    1: ["POISONSTING"],
                    5: ["SPIKES"],
                    9: ["PINMISSILE"],
                    15: ["BARBBARRAGE"],
                    21: ["WATERPULSE"],
                    26: ["DARKPULSE"],
                    29: ["POISONJAB"],
                    37: ["AQUATAIL"],
                    47: ["DOUBLEEDGE"],
                    57: ["SELFDESTRUCT"],
                },
                tutor=[
                    "ICEBALL",
                    "SPIKES",
                    "SWIFT",
                    "REST",
                    "POISONJAB",
                    "WATERPULSE",
                    "ICYWIND",
                    "SLUDGEBOMB",
                    "SHADOWBALL",
                    "AQUATAIL",
                    "ICEBEAM",
                    "DARKPULSE",
                ],
            ),
            abilities=foo("QWILFISH"),
        )
        aux["SNEASELHISUI"] = Pokemon(
            id="SNEASELHISUI",
            name="Sneasel Hisui",
            shape=bar("SNEASEL"),
            base_image="https://www.serebii.net/swordshield/pokemon/215-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/215-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/215-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/215-h.png",
            types=["FIGHT", "POISON"],
            height=0.9,
            weight=27,
            HP=55,
            ATK=95,
            DEF=55,
            SPA=35,
            SPD=75,
            SPE=115,
            evolves_to=["SNEASLER"],
            movepool=Movepool.from_dict(
                level={
                    1: ["QUICKATTACK"],
                    6: ["ROCKSMASH"],
                    11: ["SWIFT"],
                    18: ["SLASH"],
                    25: ["POISONJAB"],
                    34: ["SWORDSDANCE"],
                    43: ["CLOSECOMBAT"],
                },
                tutor=[
                    "FALSESWIPE",
                    "ROCKSMASH",
                    "AERIALACE",
                    "SWIFT",
                    "FOCUSENERGY",
                    "BULKUP",
                    "CALMMIND",
                    "REST",
                    "DRAINPUNCH",
                    "POISONJAB",
                    "XSCISSOR",
                    "SHADOWCLAW",
                    "IRONTAIL",
                    "SHADOWBALL",
                    "SNARL",
                ],
            ),
            abilities=foo("SNEASEL"),
        )
        aux["SAMUROTTHISUI"] = Pokemon(
            id="SAMUROTTHISUI",
            name="Samurott Hisui",
            shape=bar("SAMUROTT"),
            base_image="https://www.serebii.net/swordshield/pokemon/503-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/503-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/503-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/503-h.png",
            types=["WATER", "DARK"],
            height=1.5,
            weight=58.2,
            HP=90,
            ATK=108,
            DEF=80,
            SPA=100,
            SPD=65,
            SPE=85,
            evolves_from="DEWOTT",
            movepool=Movepool.from_dict(
                tutor=[
                    "FALSESWIPE",
                    "ROCKSMASH",
                    "AERIALACE",
                    "FOCUSENERGY",
                    "REST",
                    "POISONJAB",
                    "PSYCHOCUT",
                    "XSCISSOR",
                    "IRONTAIL",
                    "WATERPULSE",
                    "ICYWIND",
                    "GIGAIMPACT",
                    "AQUATAIL",
                    "MEGAHORN",
                    "HYPERBEAM",
                    "ICEBEAM",
                    "DARKPULSE",
                ],
                level={
                    0: ["NIGHTSLASH"],
                    1: ["TACKLE"],
                    6: ["AQUAJET"],
                    11: ["SWORDSDANCE"],
                    18: ["WATERPULSE"],
                    21: ["CEASELESSEDGE"],
                    25: ["SLASH"],
                    34: ["AQUATAIL"],
                    40: ["DARKPULSE"],
                    43: ["HYDROPUMP"],
                },
            ),
            abilities=foo("SAMUROTT"),
        )
        aux["LILLIGANTHISUI"] = Pokemon(
            id="LILLIGANTHISUI",
            name="Lilligant Hisui",
            shape=bar("LILLIGANT"),
            base_image="https://www.serebii.net/swordshield/pokemon/549-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/549-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/549-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/549-h.png",
            types=["GRASS", "FIGHT"],
            height=1.2,
            weight=19.2,
            HP=70,
            ATK=105,
            DEF=75,
            SPA=50,
            SPD=75,
            SPE=105,
            evolves_from="PETILIL",
            movepool=Movepool.from_dict(
                level={
                    0: ["ROCKSMASH"],
                    1: ["ABSORB"],
                    5: ["LEAFAGE"],
                    9: ["STUNSPORE"],
                    15: ["POISONPOWDER"],
                    21: ["ENERGYBALL"],
                    29: ["SLEEPPOWDER"],
                    34: ["DRAINPUNCH"],
                    37: ["RECOVER", "LEAFBLADE"],
                    42: ["VICTORYDANCE"],
                    47: ["LEAFSTORM"],
                    53: ["PETALDANCE"],
                    57: ["CLOSECOMBAT"],
                },
                tutor=[
                    "ROCKSMASH",
                    "AERIALACE",
                    "MAGICALLEAF",
                    "FOCUSENERGY",
                    "REST",
                    "BABYDOLLEYES",
                    "DRAINPUNCH",
                    "POISONJAB",
                    "ENERGYBALL",
                    "GIGAIMPACT",
                    "HYPERBEAM",
                ],
            ),
            abilities=["CHLOROPHYLL", "HUSTLE", "LEAFGUARD"],
        )
        aux["ZORUAHISUI"] = Pokemon(
            id="ZORUAHISUI",
            name="Zorua Hisui",
            shape=bar("ZORUA"),
            base_image="https://www.serebii.net/swordshield/pokemon/570-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/570-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/570-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/570-h.png",
            types=["NORMAL", "GHOST"],
            height=0.7,
            weight=12.5,
            HP=35,
            ATK=60,
            DEF=40,
            SPA=85,
            SPD=40,
            SPE=70,
            evolves_to=["ZOROARKHISUI"],
            movepool=Movepool.from_dict(
                level={
                    1: ["SHADOWSNEAK"],
                    6: ["SNARL"],
                    11: ["SWIFT"],
                    18: ["BITTERMALICE"],
                    25: ["SLASH"],
                    34: ["SHADOWCLAW"],
                    43: ["NASTYPLOT"],
                },
                tutor=[
                    "AERIALACE",
                    "SWIFT",
                    "CALMMIND",
                    "REST",
                    "SHADOWCLAW",
                    "SLUDGEBOMB",
                    "SHADOWBALL",
                    "SNARL",
                    "DARKPULSE",
                ],
            ),
            abilities=foo("ZORUA"),
        )
        aux["ZOROARKHISUI"] = Pokemon(
            id="ZOROARKHISUI",
            name="Zoroark Hisui",
            shape=bar("ZOROARK"),
            base_image="https://www.serebii.net/swordshield/pokemon/571-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/571-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/571-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/571-h.png",
            types=["NORMAL", "GHOST"],
            height=1.6,
            weight=73,
            HP=55,
            ATK=100,
            DEF=60,
            SPA=125,
            SPD=60,
            SPE=110,
            evolves_from="ZORUAHISUI",
            movepool=Movepool.from_dict(
                level={
                    1: ["SHADOWSNEAK"],
                    6: ["SNARL"],
                    11: ["SWIFT"],
                    18: ["BITTERMALICE"],
                    25: ["SLASH"],
                    34: ["SHADOWCLAW"],
                    40: ["SHADOWBALL"],
                    43: ["NASTYPLOT"],
                    52: ["EXTRASENSORY"],
                },
                tutor=[
                    "ROCKSMASH",
                    "AERIALACE",
                    "SWIFT",
                    "OMINOUSWIND",
                    "CALMMIND",
                    "REST",
                    "SHADOWCLAW",
                    "SLUDGEBOMB",
                    "SHADOWBALL",
                    "SNARL",
                    "GIGAIMPACT",
                    "HYPERBEAM",
                    "FLAMETHROWER",
                    "DARKPULSE",
                ],
            ),
            abilities=foo("ZOROARK"),
        )
        aux["BRAVIARYHISUI"] = Pokemon(
            id="BRAVIARYHISUI",
            name="Braviary Hisui",
            base_image="https://www.serebii.net/swordshield/pokemon/628-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/628-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/628-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/628-h.png",
            types=["PSYCHIC", "FLYING"],
            height=1.7,
            weight=43.4,
            HP=110,
            ATK=83,
            DEF=70,
            SPA=112,
            SPD=70,
            SPE=65,
            evolves_from="RUFFLET",
            movepool=Movepool.from_dict(
                level={
                    1: ["QUICKATTACK"],
                    6: ["AERIALACE"],
                    11: ["TWISTER"],
                    18: ["SLASH"],
                    20: ["AIRSLASH"],
                    25: ["ESPERWING", "ROOST"],
                    34: ["DOUBLEEDGE"],
                    43: ["BRAVEBIRD"],
                    52: ["HURRICANE"],
                },
                tutor=[
                    "ROCKSMASH",
                    "AERIALACE",
                    "SWIFT",
                    "OMINOUSWIND",
                    "POWERSHIFT",
                    "BULKUP",
                    "REST",
                    "ZENHEADBUTT",
                    "ROCKSLIDE",
                    "SHADOWCLAW",
                    "MYSTICALFIRE",
                    "DAZZLINGGLEAM",
                    "GIGAIMPACT",
                    "HYPERBEAM",
                    "PSYCHIC",
                ],
            ),
            abilities=["KEENEYE", "SHEERFORCE", "DEFIANT"],
        )
        aux["SLIGGOOHISUI"] = Pokemon(
            id="SLIGGOOHISUI",
            name="Sliggoo Hisui",
            shape=bar("SLIGGOO"),
            base_image="https://www.serebii.net/swordshield/pokemon/705-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/705-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/705-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/705-h.png",
            types=["DRAGON", "STEEL"],
            height=0,
            weight=0,
            HP=58,
            ATK=75,
            DEF=83,
            SPA=83,
            SPD=113,
            SPE=40,
            evolves_from="GOOMY",
            evolves_to=["GOODRAHISUI"],
            movepool=Movepool.from_dict(
                level={
                    1: ["BUBBLE"],
                    6: ["ACIDSPRAY"],
                    11: ["ACIDARMOR"],
                    18: ["WATERPULSE"],
                    25: ["IRONHEAD", "DRAGONPULSE"],
                    34: ["SHELTER"],
                    43: ["HYDROPUMP"],
                },
                tutor=[
                    "REST",
                    "ROCKSLIDE",
                    "IRONHEAD",
                    "IRONTAIL",
                    "WATERPULSE",
                    "SLUDGEBOMB",
                    "OUTRAGE",
                    "THUNDERBOLT",
                    "ICEBEAM",
                    "DRACOMETEOR",
                    "STEELBEAM",
                ],
            ),
            abilities=["SAPSIPPER", "OVERCOAT", "GOOEY"],
        )
        aux["GOODRAHISUI"] = Pokemon(
            id="GOODRAHISUI",
            name="Goodra Hisui",
            shape=bar("GOODRA"),
            base_image="https://www.serebii.net/swordshield/pokemon/706-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/706-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/706-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/706-h.png",
            types=["DRAGON", "STEEL"],
            height=1.7,
            weight=334.1,
            HP=80,
            ATK=100,
            DEF=100,
            SPA=110,
            SPD=150,
            SPE=60,
            evolves_from="SLIGGOOHISUI",
            movepool=Movepool.from_dict(
                level={
                    1: ["BUBBLE"],
                    6: ["ACIDSPRAY"],
                    11: ["ACIDARMOR"],
                    18: ["WATERPULSE"],
                    25: ["IRONHEAD", "DRAGONPULSE"],
                    34: ["SHELTER"],
                    43: ["HYDROPUMP"],
                },
                tutor=[
                    "ROCKSMASH",
                    "BULLDOZE",
                    "REST",
                    "FIREPUNCH",
                    "THUNDERPUNCH",
                    "ROCKSLIDE",
                    "IRONHEAD",
                    "IRONTAIL",
                    "WATERPULSE",
                    "SLUDGEBOMB",
                    "GIGAIMPACT",
                    "OUTRAGE",
                    "HYPERBEAM",
                    "FLAMETHROWER",
                    "THUNDERBOLT",
                    "ICEBEAM",
                    "DRACOMETEOR",
                    "STEELBEAM",
                ],
            ),
            abilities=["SAPSIPPER", "OVERCOAT", "GOOEY"],
        )
        aux["AVALUGGHISUI"] = Pokemon(
            id="AVALUGGHISUI",
            name="Avalugg Hisui",
            shape=bar("AVALUGG"),
            base_image="https://www.serebii.net/swordshield/pokemon/713-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/713-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/713-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/713-h.png",
            types=["ICE", "ROCK"],
            height=1.4,
            weight=262.4,
            HP=0,
            ATK=0,
            DEF=0,
            SPA=0,
            SPD=0,
            SPE=0,
            evolves_from="BERGMITE",
            movepool=Movepool.from_dict(
                level={
                    0: ["ROCKSLIDE"],
                    1: ["TACKLE"],
                    5: ["POWDERSNOW"],
                    9: ["ICESHARD"],
                    15: ["BITE"],
                    21: ["IRONDEFENSE"],
                    29: ["CRUNCH", "EARTHPOWER"],
                    37: ["MOUNTAINGALE", "BLIZZARD"],
                    47: ["DOUBLEEDGE"],
                },
                tutor=[
                    "ICEFANG",
                    "ICEBALL",
                    "ROCKSMASH",
                    "BULLDOZE",
                    "STEALTHROCK",
                    "POWERSHIFT",
                    "REST",
                    "ROCKSLIDE",
                    "IRONHEAD",
                    "WATERPULSE",
                    "ICYWIND",
                    "EARTHPOWER",
                    "FLASHCANNON",
                    "GIGAIMPACT",
                    "HIGHHORSEPOWER",
                    "STONEEDGE",
                    "HYPERBEAM",
                    "ICEBEAM",
                ],
            ),
            abilities=["STRONGJAW", "ICEBODY", "STURDY"],
        )
        aux["DECIDUEYEHISUI"] = Pokemon(
            id="DECIDUEYEHISUI",
            name="Decidueye Hisui",
            shape=bar("DECIDUEYE"),
            base_image="https://www.serebii.net/swordshield/pokemon/724-h.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/724-h.png",
            female_image="https://www.serebii.net/swordshield/pokemon/724-h.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/724-h.png",
            types=["GRASS", "FIGHT"],
            height=1.6,
            weight=37,
            HP=88,
            ATK=112,
            DEF=80,
            SPA=95,
            SPD=95,
            SPE=60,
            evolves_from="DARTRIX",
            movepool=Movepool.from_dict(
                level={
                    0: ["ROCKSMASH"],
                    1: ["GUST"],
                    6: ["LEAFAGE"],
                    11: ["ROOST"],
                    18: ["AERIALACE"],
                    21: ["MAGICALLEAF"],
                    25: ["AIRSLASH"],
                    30: ["AURASPHERE"],
                    34: ["LEAFBLADE", "TRIPLEARROWS"],
                    40: ["BRAVEBIRD"],
                    43: ["LEAFSTORM"],
                },
                tutor=[
                    "FALSESWIPE",
                    "ROCKSMASH",
                    "SPIKES",
                    "AERIALACE",
                    "SWIFT",
                    "MAGICALLEAF",
                    "FOCUSENERGY",
                    "BULKUP",
                    "REST",
                    "PSYCHOCUT",
                    "SHADOWCLAW",
                    "ENERGYBALL",
                    "GIGAIMPACT",
                    "HYPERBEAM",
                ],
            ),
            abilities=foo("DECIDUEYE"),
        )
        aux["WYRDEER"] = Pokemon(
            id="WYRDEER",
            name="Wyrdeer",
            shape=bar("STANTLER"),
            base_image="https://www.serebii.net/swordshield/pokemon/899.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/899.png",
            female_image="https://www.serebii.net/swordshield/pokemon/899.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/899.png",
            types=["NORMAL", "PSYCHIC"],
            height=1.8,
            weight=95.1,
            HP=103,
            ATK=105,
            DEF=72,
            SPA=105,
            SPD=75,
            SPE=65,
            evolves_from="STANTLER",
            movepool=Movepool.from_dict(
                level={
                    1: ["TACKLE"],
                    5: ["CONFUSION"],
                    9: ["HYPNOSIS"],
                    15: ["CALMMIND"],
                    21: ["PSYSHIELDBASH"],
                    29: ["EXTRASENSORY"],
                    37: ["ZENHEADBUTT"],
                    47: ["DOUBLEEDGE"],
                },
                tutor=[
                    "BULLDOZE",
                    "SWIFT",
                    "CALMMIND",
                    "REST",
                    "ZENHEADBUTT",
                    "IRONTAIL",
                    "CHARGEBEAM",
                    "ENERGYBALL",
                    "SHADOWBALL",
                    "GIGAIMPACT",
                    "WILDCHARGE",
                    "HIGHHORSEPOWER",
                    "MEGAHORN",
                    "HYPERBEAM",
                    "THUNDERBOLT",
                    "PSYCHIC",
                ],
            ),
            abilities=["INTIMIDATE", "FRISK", "SAPSIPPER"],
        )
        aux["KLEAVOR"] = Pokemon(
            id="KLEAVOR",
            name="Kleavor",
            shape=bar("SCYTHER"),
            base_image="https://www.serebii.net/swordshield/pokemon/900.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/900.png",
            female_image="https://www.serebii.net/swordshield/pokemon/900.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/900.png",
            types=["BUG", "ROCK"],
            height=1.8,
            weight=89,
            HP=70,
            ATK=135,
            DEF=95,
            SPA=45,
            SPD=70,
            SPE=85,
            evolves_from="SCYTHER",
            movepool=Movepool.from_dict(
                level={
                    1: ["QUICKATTACK"],
                    6: ["SILVERWIND"],
                    11: ["AERIALACE"],
                    14: ["DOUBLEHIT", "STEALTHROCK"],
                    18: ["AIRSLASH"],
                    25: ["SWORDSDANCE"],
                    29: ["STONEAXE"],
                    34: ["XSCISSOR"],
                    43: ["CLOSECOMBAT"],
                },
                tutor=[
                    "FALSESWIPE",
                    "ROCKSMASH",
                    "AERIALACE",
                    "STEALTHROCK",
                    "SWIFT",
                    "OMINOUSWIND",
                    "FOCUSENERGY",
                    "CALMMIND",
                    "REST",
                    "PSYCHOCUT",
                    "XSCISSOR",
                    "ROCKSLIDE",
                    "GIGAIMPACT",
                    "STONEEDGE",
                    "HYPERBEAM",
                ],
            ),
            abilities=foo("SCYTHER"),
        )
        aux["URSALUNA"] = Pokemon(
            id="URSALUNA",
            name="Ursaluna",
            shape=bar("URSARING"),
            base_image="https://www.serebii.net/swordshield/pokemon/901.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/901.png",
            female_image="https://www.serebii.net/swordshield/pokemon/901.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/901.png",
            types=["GROUND", "NORMAL"],
            height=0,
            weight=0,
            HP=130,
            ATK=140,
            DEF=105,
            SPA=45,
            SPD=80,
            SPE=50,
            evolves_from="URSARING",
            movepool=Movepool.from_dict(
                level={
                    1: ["TACKLE"],
                    6: ["BABYDOLL EYES"],
                    11: ["BULLDOZE"],
                    18: ["SLASH"],
                    25: ["PLAYROUGH"],
                    34: ["HIGHHORSEPOWER"],
                    43: ["DOUBLEEDGE", "HEADLONGRUSH"],
                },
                tutor=[
                    "ROCKSMASH",
                    "BULLDOZE",
                    "AERIALACE",
                    "SWIFT",
                    "FOCUSENERGY",
                    "BULKUP",
                    "REST",
                    "BABYDOLLEYES",
                    "FIREPUNCH",
                    "THUNDERPUNCH",
                    "ICEPUNCH",
                    "ROCKSLIDE",
                    "SHADOWCLAW",
                    "EARTHPOWER",
                    "GIGAIMPACT",
                    "HIGHHORSEPOWER",
                    "STONEEDGE",
                    "PLAYROUGH",
                    "HYPERBEAM",
                ],
            ),
            abilities=["GUTS", "BULLETPROOF", "UNNERVE"],
        )
        aux["BASCULEGION"] = Pokemon(
            id="BASCULEGION",
            name="Basculegion",
            shape=bar("BASCULIN"),
            base_image="https://www.serebii.net/swordshield/pokemon/902.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/902.png",
            female_image="https://www.serebii.net/swordshield/pokemon/902-f.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/902-f.png",
            types=["WATER", "GHOST"],
            height=3,
            weight=110,
            HP=120,
            ATK=112,
            DEF=65,
            SPA=80,
            SPD=75,
            SPE=78,
            movepool=Movepool.from_dict(
                level={
                    1: ["TACKLE"],
                    6: ["AQUAJET"],
                    11: ["BITE", "HEX"],
                    18: ["ZENHEADBUTT"],
                    25: ["CRUNCH", "SHADOWBALL"],
                    34: ["WAVECRASH"],
                    43: ["DOUBLEEDGE"],
                },
                tutor=[
                    "ICEFANG",
                    "SWIFT",
                    "OMINOUSWIND",
                    "CALMMIND",
                    "REST",
                    "ZENHEADBUTT",
                    "WATERPULSE",
                    "ICYWIND",
                    "SHADOWBALL",
                    "GIGAIMPACT",
                    "AQUATAIL",
                    "HYPERBEAM",
                    "ICEBEAM",
                    "PSYCHIC",
                ],
            ),
            abilities=foo("BASCULIN"),
        )
        aux["SNEASLER"] = Pokemon(
            id="SNEASLER",
            name="Sneasler",
            shape=bar("SNEASEL"),
            base_image="https://www.serebii.net/swordshield/pokemon/903.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/903.png",
            female_image="https://www.serebii.net/swordshield/pokemon/903.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/903.png",
            types=["FIGHT", "POISON"],
            height=1.3,
            weight=43,
            HP=80,
            ATK=130,
            DEF=60,
            SPA=40,
            SPD=80,
            SPE=120,
            evolves_from="SNEASELHISUI",
            movepool=Movepool.from_dict(
                level={
                    1: ["QUICKATTACK"],
                    6: ["ROCKSMASH"],
                    11: ["SWIFT", "DIRECLAW"],
                    18: ["SLASH"],
                    25: ["POISONJAB"],
                    34: ["SWORDSDANCE"],
                    43: ["CLOSECOMBAT"],
                },
                tutor=[
                    "FALSESWIPE",
                    "ROCKSMASH",
                    "AERIALACE",
                    "SWIFT",
                    "POWERSHIFT",
                    "FOCUSENERGY",
                    "BULKUP",
                    "CALMMIND",
                    "REST",
                    "DRAINPUNCH",
                    "POISONJAB",
                    "XSCISSOR",
                    "SHADOWCLAW",
                    "IRONTAIL",
                    "SHADOWBALL",
                    "SNARL",
                    "GIGAIMPACT",
                    "HYPERBEAM",
                ],
            ),
            abilities=["PRESSURE", "POISONTOUCH"],
        )
        aux["OVERQWIL"] = Pokemon(
            id="OVERQWIL",
            name="Overqwil",
            shape=bar("QWILFISH"),
            base_image="https://www.serebii.net/swordshield/pokemon/904.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/904.png",
            female_image="https://www.serebii.net/swordshield/pokemon/904.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/904.png",
            types=["DARK", "POISON"],
            height=0,
            weight=0,
            HP=80,
            ATK=130,
            DEF=60,
            SPA=40,
            SPD=80,
            SPE=120,
            evolves_from="QWILFISH",
            movepool=Movepool.from_dict(
                level={
                    1: ["POISONSTING"],
                    5: ["SPIKES"],
                    9: ["PINMISSILE"],
                    15: ["BARBBARRAGE"],
                    21: ["WATERPULSE"],
                    26: ["DARKPULSE"],
                    29: ["POISONJAB"],
                    37: ["AQUATAIL"],
                    47: ["DOUBLEEDGE"],
                    57: ["SELFDESTRUCT"],
                },
                tutor=[
                    "ICEBALL",
                    "SPIKES",
                    "SWIFT",
                    "REST",
                    "POISONJAB",
                    "WATERPULSE",
                    "ICYWIND",
                    "SLUDGEBOMB",
                    "SHADOWBALL",
                    "GIGAIMPACT",
                    "AQUATAIL",
                    "HYPERBEAM",
                    "ICEBEAM",
                    "DARKPULSE",
                ],
            ),
            abilities=foo("QWILFISH"),
        )
        aux["ENAMORUS"] = Legendary(
            id="ENAMORUS",
            name="Enamorus",
            shape=bar("LANDORUS"),
            base_image="https://www.serebii.net/swordshield/pokemon/905.png",
            base_image_shiny="https://www.serebii.net/Shiny/SWSH/905.png",
            female_image="https://www.serebii.net/swordshield/pokemon/905.png",
            female_image_shiny="https://www.serebii.net/Shiny/SWSH/905.png",
            types=["FAIRY", "FLYING"],
            height=1.6,
            weight=48,
            HP=75,
            ATK=115,
            DEF=110,
            SPA=135,
            SPD=100,
            SPE=46,
            movepool=Movepool.from_dict(
                level={
                    1: ["TACKLE"],
                    7: ["BITE"],
                    11: ["TWISTER"],
                    14: ["DRAININGKISS"],
                    22: ["IRONDEFENSE"],
                    31: ["EXTRASENSORY"],
                    41: ["CRUNCH"],
                    47: ["MOONBLAST"],
                    52: ["SPRINGTIDESTORM"],
                },
                tutor=[
                    "ROCKSMASH",
                    "POWERSHIFT",
                    "CALMMIND",
                    "REST",
                    "ZENHEADBUTT",
                    "MYSTICALFIRE",
                    "SLUDGEBOMB",
                    "EARTHPOWER",
                    "DAZZLINGGLEAM",
                    "GIGAIMPACT",
                    "PLAYROUGH",
                    "HYPERBEAM",
                    "PSYCHIC",
                ],
            ),
            abilities=foo("QWILFISH"),
        )

    with open(DIR, mode="w") as file2:
        dump(
            list(aux.values()),
            fp=file2,
            indent=4,
            cls=SpeciesEncoder,
            sort_keys=False,
        )
